### PR TITLE
Add mass update feature

### PR DESCRIPTION
**Pull request by yassinebourakba**
This PR adds the ability to do a mass update or patch to your Airtable data.

Both patch() and update() arguments are dynamic. 

- In order to update a single is unchanged and still
``` php
Airtable::table('companies')->update('rec5N7fr8GhDtdNxx', ['country' => 'US']);
```

- In order to update multiple records only an array of data is required
``` php
Airtable::table('companies')->patch([
    [
        'id' => 'rec5N7fr8GhDtdNxx',
        'fields' => ['country' => 'US']
    ],
    [
        'id' => 'rec8BhDt4fs2',
        'fields' => ['country' => 'UK']
    ],
    ...
]);
```

### CODE REVIEW

**Review by swilla — CHANGES_REQUESTED** [review]
This looks good, but I think we need to bump up the PHP compatibility to 7.4 in the composer.json with the spread operator.

**Comment by yassinebourakba** [comment]
@swilla PHP version is set to `^7.1`, I believe it's equivalent to `>=7.1 and <8.0`. So version `7.4` is already included

**Comment by swilla** [comment]
> @swilla PHP version is set to `^7.1`, I believe it's equivalent to `>=7.1 and <8.0`. So version `7.4` is already included

I think we need to bump it up to `^7.4` as that code won't work on earlier versions of PHP.

**Comment by yassinebourakba** [comment]
> > @swilla PHP version is set to `^7.1`, I believe it's equivalent to `>=7.1 and <8.0`. So version `7.4` is already included
> 
> I think we need to bump it up to `^7.4` as that code won't work on earlier versions of PHP.

Alright ! so should I make it  "php": "^7.4" or  "php": "^7.1 || ^7.4"

**Review by swilla — APPROVED** [review]

**Pull request merged**
